# Generated by Django 4.1 on 2023-11-19 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dc", models.CharField(max_length=250, null=True)),
                ("dci", models.CharField(max_length=250, null=True)),
                ("forme", models.CharField(max_length=50)),
                ("dosage", models.IntegerField(null=True)),
                ("presentation", models.TextField(null=True)),
                ("classe_therapeutique", models.TextField(null=True)),
                ("voie_administration", models.TextField(null=True)),
                ("fabricant", models.TextField(null=True)),
                ("titulaire_amm", models.TextField(null=True)),
                ("code_amm", models.TextField(null=True)),
                ("expiration_amm", models.DateField(null=True)),
                ("pght", models.IntegerField(null=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Produit.categorie",
                    ),
                ),
            ],
        ),
    ]
