# Generated by Django 4.1 on 2023-11-19 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Demandeur", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=25)),
            ],
            options={
                "verbose_name": "demandeur",
                "verbose_name_plural": "demandeurs",
            },
        ),
        migrations.CreateModel(
            name="Type_expediteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Voie_entree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Demande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_expediteur", models.CharField(max_length=50, null=True)),
                ("adresse_expediteur", models.CharField(max_length=50, null=True)),
                ("nom_transitaire", models.CharField(max_length=50, null=True)),
                ("adresse_transitaire", models.CharField(max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "demandeur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Demandeur.demandeur",
                    ),
                ),
                (
                    "statut",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Demande.statut",
                    ),
                ),
                (
                    "type_expediteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Demande.type_expediteur",
                    ),
                ),
                (
                    "voie_entree",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Demande.voie_entree",
                    ),
                ),
            ],
        ),
    ]
