# Generated by Django 4.1 on 2023-12-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Demande", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="demande",
            name="date_soumission",
            field=models.DateTimeField(null=True),
        ),
    ]
