# Generated by Django 4.1 on 2023-12-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Demande", "0003_traitement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type_demande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=150)),
            ],
        ),
    ]
