# Generated by Django 4.1 on 2023-12-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Demande", "0006_remove_demande_nature_impression"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signataire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_signataire", models.TextField(null=True)),
                ("fonction", models.TextField(null=True)),
                ("signature", models.TextField(null=True)),
                ("url_base", models.TextField(null=True)),
            ],
        ),
    ]
