# Generated by Django 4.1 on 2023-12-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Demande", "0004_type_demande"),
    ]

    operations = [
        migrations.CreateModel(
            name="ASE",
            fields=[
                (
                    "demande_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Demande.demande",
                    ),
                ),
                ("facture_proforma", models.TextField(null=True)),
                ("certicat_bonne_pratique", models.TextField(null=True)),
                ("certificat_analyse_prod", models.TextField(null=True)),
                ("certificat_origine_prod", models.TextField(null=True)),
                ("certificat_atestation_don", models.TextField(null=True)),
                ("total_item", models.IntegerField(null=True)),
            ],
            bases=("Demande.demande",),
        ),
    ]
