# Generated by Django 4.1 on 2023-11-19 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Produit", "0001_initial"),
        ("Demande", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ASI",
            fields=[
                (
                    "demande_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Demande.demande",
                    ),
                ),
                (
                    "facture_proforma",
                    models.FileField(max_length=50, null=True, upload_to="media/ASI"),
                ),
                (
                    "certicat_bonne_pratique",
                    models.FileField(null=True, upload_to="media/ASI"),
                ),
                (
                    "certificat_analyse_prod",
                    models.FileField(null=True, upload_to="media/ASI"),
                ),
                (
                    "certificat_origine_prod",
                    models.FileField(null=True, upload_to="media/ASI"),
                ),
                (
                    "certificat_atestation_don",
                    models.FileField(null=True, upload_to="media/ASI"),
                ),
                ("num_quittance", models.CharField(max_length=100, null=True)),
                ("copie_quittance", models.FileField(null=True, upload_to="media/ASI")),
            ],
            bases=("Demande.demande",),
        ),
        migrations.CreateModel(
            name="Produit_asi",
            fields=[
                (
                    "asi_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ASI.asi",
                    ),
                ),
                ("dc", models.CharField(max_length=250, null=True)),
                ("dci", models.CharField(max_length=250, null=True)),
                ("forme", models.CharField(max_length=50)),
                ("dosage", models.IntegerField(null=True)),
                ("presentation", models.TextField(null=True)),
                ("quantite", models.IntegerField(null=True)),
                ("cout", models.IntegerField(null=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Produit.categorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
            },
            bases=("ASI.asi",),
        ),
    ]
