# Generated by Django 4.1 on 2023-11-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ASI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit_asi",
            name="amm",
            field=models.BooleanField(default=False),
        ),
    ]
