# Generated by Django 4.1 on 2023-11-23 22:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ASI", "0002_produit_asi_amm"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Produit_asi",
        ),
    ]
