# Generated by Django 4.1 on 2023-11-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ASI", "0003_delete_produit_asi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asi",
            name="certicat_bonne_pratique",
            field=models.FileField(null=True, upload_to="media/ASI/BP/"),
        ),
        migrations.AlterField(
            model_name="asi",
            name="certificat_analyse_prod",
            field=models.FileField(null=True, upload_to="media/ASI/AP/"),
        ),
        migrations.AlterField(
            model_name="asi",
            name="certificat_atestation_don",
            field=models.FileField(null=True, upload_to="media/ASI/AD/"),
        ),
        migrations.AlterField(
            model_name="asi",
            name="certificat_origine_prod",
            field=models.FileField(null=True, upload_to="media/ASI/OP/"),
        ),
        migrations.AlterField(
            model_name="asi",
            name="facture_proforma",
            field=models.FileField(
                max_length=50, null=True, upload_to="media/ASI/Proforma/"
            ),
        ),
    ]
