# Generated by Django 4.1 on 2023-12-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ASI", "0004_alter_asi_certicat_bonne_pratique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asi",
            name="cout",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="asi",
            name="quantite",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="asi",
            name="copie_quittance",
            field=models.FileField(null=True, upload_to="media/ASI/Quittance"),
        ),
    ]
