# Generated by Django 4.1 on 2023-12-01 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ASI", "0005_asi_cout_asi_quantite_alter_asi_copie_quittance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asi",
            old_name="quantite",
            new_name="nombre",
        ),
    ]
