# Generated by Django 4.1 on 2023-12-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ASI", "0008_alter_asi_certicat_bonne_pratique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asi",
            name="certicat_bonne_pratique",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="asi",
            name="certificat_analyse_prod",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="asi",
            name="certificat_atestation_don",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="asi",
            name="certificat_origine_prod",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="asi",
            name="copie_quittance",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="asi",
            name="facture_proforma",
            field=models.TextField(null=True),
        ),
    ]
