# Generated by Django 4.1 on 2023-11-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Demandeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tel", models.IntegerField(null=True)),
                ("ville", models.CharField(default="OUAGADOUGOU", max_length=50)),
                ("structure", models.CharField(max_length=50)),
            ],
        ),
    ]
