# Generated by Django 4.1 on 2023-12-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocole",
            name="nom",
            field=models.CharField(max_length=25),
        ),
    ]
