# Generated by Django 4.1 on 2023-12-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emailing", "0002_alter_protocole_nom"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(null=True)),
                ("type_demande", models.IntegerField(null=True)),
            ],
        ),
    ]
