# Generated by Django 4.1 on 2023-12-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emailing", "0005_emailmessage_objet"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="modif_url",
            field=models.TextField(null=True),
        ),
    ]
